import React, { createContext, useContext, useState, useEffect } from 'react';

const STORAGE_KEY = 'devibe_lang';
const LanguageContext = createContext();

export const translations = {
  ko: {
    nav: { services: 'SERVICES', references: 'DESIGNS', portfolio: 'PORTFOLIO', about: 'ABOUT', contact: 'CONTACT' },
    hero: {
      heroCard: {
        headerBar: 'devvibe — main',
        ariaLabel: '개발자 프로필 코드 카드',
        files: [
          {
            key: 'profile',
            name: 'profile.ts',
            lang: 'TypeScript',
            lines: [
              { kind: 'comment',     code: '// 그냥 해봐! — Just go for it.',                          accent: 'comment' },
              { kind: 'spacer',      code: '',                                                          accent: 'comment' },
              { kind: 'keyword',     code: 'export const profile = {',                                  accent: 'keyword' },
              { kind: 'declaration', code: '  name: "DEVIBE",',                                         accent: 'string'  },
              { kind: 'declaration', code: '  role: "프리랜서 풀스택 개발자",',                         accent: 'string'  },
              { kind: 'array',       code: '  builds: ["홈페이지", "쇼핑몰", "관리자 시스템", "랜딩"],', accent: 'string'  },
              { kind: 'declaration', code: '  stack: ["React", "Node", "TypeScript", "PostgreSQL"],',   accent: 'string'  },
              { kind: 'declaration', code: '  status: "available",  // 이번 달 1건 접수 가능',          accent: 'string'  },
              { kind: 'declaration', code: '  reply: "24h on weekdays",',                               accent: 'string'  },
              { kind: 'declaration', code: '  contact: "/contact",',                                    accent: 'string'  },
              { kind: 'keyword',     code: '};',                                                        accent: 'keyword' },
            ],
          },
          {
            key: 'stack',
            name: 'stack.ts',
            lang: 'TypeScript',
            lines: [
              { kind: 'comment',     code: '// 사용하는 기술 스택' },
              { kind: 'spacer',      code: '' },
              { kind: 'keyword',     code: 'export const stack = {' },
              { kind: 'declaration', code: '  frontend: ["React", "Next.js", "TypeScript", "Tailwind"],' },
              { kind: 'declaration', code: '  backend:  ["Node.js", "Express", "PostgreSQL", "Redis"],' },
              { kind: 'declaration', code: '  cloud:    ["AWS", "Render", "Vercel", "Cloudflare"],' },
              { kind: 'declaration', code: '  tools:    ["Docker", "GitHub Actions", "Figma"],' },
              { kind: 'declaration', code: '  yearsExp: 3,' },
              { kind: 'keyword',     code: '};' },
            ],
          },
          {
            key: 'status',
            name: 'status.ts',
            lang: 'TypeScript',
            lines: [
              { kind: 'comment',     code: '// 이번 달 작업 가용 현황' },
              { kind: 'spacer',      code: '' },
              { kind: 'keyword',     code: 'export const status = {' },
              { kind: 'declaration', code: '  available: true,' },
              { kind: 'declaration', code: '  slotsThisMonth: 1,' },
              { kind: 'declaration', code: '  replyTime: "24h on weekdays",' },
              { kind: 'declaration', code: '  currentProjects: 2,' },
              { kind: 'declaration', code: '  nextSlotFrom: "available now",' },
              { kind: 'declaration', code: '  contact: "/contact",' },
              { kind: 'keyword',     code: '};' },
            ],
          },
        ],
        sidebar: {
          explorerLabel: 'EXPLORER',
          projectLabel: 'DEV.VIBE',
          folders: [
            { name: 'src', files: ['profile.ts', 'stack.ts', 'status.ts'] },
            { name: 'docs', files: ['README.md'] },
          ],
        },
        statusBar: {
          branch: 'main',
          errors: 0,
          warnings: 0,
          encoding: 'UTF-8',
          liveLabel: 'Live',
          paletteHint: '⌘K',
          paletteTooltip: '명령 팔레트 (Ctrl/⌘ + K)',
        },
        primaryCta: '상담 시작하기 →',
        secondaryCta: '포트폴리오 보기',
      },
    },
    intro: {
      label: 'WHO WE ARE',
      title: '기업 홈페이지가 필요할 때\n먼저 떠올리는 브랜드',
      desc: '홈페이지공방은 PC와 모바일에서 고객 문의가 끊기지 않도록 화면을 맞추고, 회사 운영에 필요한 관리자·예약·연동 기능을 직접 만들며, 납품 이후에도 계속 관리해 드리는 홈페이지 파트너입니다. 필요할 때 확장 가능한 구조로 만들어, 다음 담당자가 와도 계속 이어갈 수 있습니다.',
    },
    about: {
      mission: '홈페이지공방은 PC와 모바일에서 고객 문의가 잘 이어지도록 반응형 기업 홈페이지를 만들고, 필요한 관리자·예약·연동 기능을 직접 개발하며, 납품 후에도 계속 관리하는 홈페이지 파트너입니다.',
    },
    parallaxBridge: {
      top: '홈페이지공방 · CRAFTED IN CODE',
      bottom: 'MADE TO LAST · SINCE 2026',
    },
    comingSoon: {
      label: '준비중',
      title: '조금만 기다려주세요!',
      body: '해당 기능은 마무리 작업 중이에요. 곧 오픈 예정이며, 그동안은 이메일이나 카카오 오픈 채팅으로 편하게 문의해주세요.',
      aiPreviewTitle: 'AI 시안 생성 기능은 준비 중이에요',
      aiPreviewBody: '내부 테스트를 진행 중이에요. 곧 오픈 예정이며, 그동안은 아래 상담 폼으로 원하시는 홈페이지 방향을 알려주시면 사람이 직접 초안을 만들어 드립니다.',
      contactCta: '지금 바로 상담하기',
    },
    customerProblems: {
      eyebrow: '> problems/',
      headline: '이런 고민, 익숙하시죠?',
      caption: '홈페이지공방은 이 세 가지에 정답을 준비합니다.',
      cards: [
        {
          num: '문제 01',
          problem: '모바일에서 문의가 자꾸 유실돼요',
          solution: 'PC와 모바일 어디서든 문의와 예약이 끊기지 않도록 화면을 맞추고, 문의폼은 3초 안에 열리도록 최적화합니다.',
        },
        {
          num: '문제 02',
          problem: '관리자 기능이 없어서 매번 개발자에게 부탁해야 해요',
          solution: '반복 업무를 줄이는 관리자 기능과 자동화를 함께 개발해, 콘텐츠 수정을 직접 하실 수 있습니다.',
        },
        {
          num: '문제 03',
          problem: '개발자가 떠나면 홈페이지 관리가 곤란해질까 걱정입니다',
          solution: '계약서에 소스코드 인도와 데이터 귀속을 명시하고, 납품 후 30일 무상 하자 보수와 월 유지관리 상품을 제공합니다.',
        },
      ],
    },
    trustCompliance: {
      ariaLabel: '계약·유지관리 안내',
      items: [
        { icon: '[ 01 ]', label: '1인 프리랜서 계약', sub: '원천징수 3.3% 처리 가능' },
        { icon: '[ 02 ]', label: '소스코드 인도', sub: '계약서에 명시' },
        { icon: '[ 03 ]', label: '30일 무상 하자보수', sub: '납품 후 자동 적용' },
        { icon: '[ 04 ]', label: '월 유지관리 상품', sub: '12만~50만원/월' },
      ],
    },
    starterProducts: {
      eyebrow: '> starter/',
      headline: '빠르게 시작할 수 있는 소형 상품',
      caption: '본격 기업 홈페이지 전에 먼저 감을 잡고 싶다면. 체험 후 정식 계약으로 전환할 수 있습니다.',
      tagLabel: 'STARTER',
      discountLabel: '80% 할인',
      list: [
        {
          name: '랜딩 페이지 1장',
          body: '제품·이벤트 홍보 원페이지. 반응형·문의폼 포함.',
          listPrice: '150만원',
          price: '30만원~',
          cta: '상담 시작 →',
          prefill: {
            projectType: '웹 개발',
            budget: '100만원 이하',
            description: '[STARTER] 랜딩 페이지 1장 상담 요청드립니다. (제품·이벤트 홍보 원페이지, 반응형·문의폼 포함)',
          },
        },
        {
          name: '명함형 사이트 3페이지',
          body: '회사소개·서비스·연락처. 기본 SEO·배포 포함.',
          listPrice: '200만원',
          price: '40만원~',
          cta: '상담 시작 →',
          prefill: {
            projectType: '웹 개발',
            budget: '100만원 이하',
            description: '[STARTER] 명함형 사이트 3페이지 상담 요청드립니다. (회사소개·서비스·연락처, 기본 SEO·배포 포함)',
          },
        },
        {
          name: '문의폼 세트',
          body: '기존 사이트에 문의폼·자동회신 이메일 추가.',
          listPrice: '125만원',
          price: '25만원~',
          cta: '상담 시작 →',
          prefill: {
            projectType: '유지보수',
            budget: '100만원 이하',
            description: '[STARTER] 문의폼 세트 상담 요청드립니다. (기존 사이트에 문의폼·자동회신 이메일 추가)',
          },
        },
      ],
      bridge: '> 본격 기업 홈페이지가 필요하다면 아래 상품을 참고하세요 ↓',
    },
    services: {
      label: 'SERVICES',
      title: '필요한 홈페이지,\n바로 제작해드립니다',
      list: [
        {
          key: 'landing', title: 'Landing Page', titleKo: '랜딩 페이지',
          desc: '제품·캠페인을 위한 단일 페이지. 전환율과 로딩 속도에 초점, 1~2주 안에 라이브.',
          tagline: '신규 제품·이벤트를 빠르게 알리고, 방문자가 바로 행동하게 만드는 한 페이지',
          features: ['반응형 디자인 (PC·모바일)', '문의·예약 폼 + 자동 이메일', '구글 애널리틱스/픽셀 연동', '기본 SEO 세팅', '도메인·HTTPS·CDN 배포', '간단 콘텐츠 수정 가이드'],
          tech: ['React', 'Next.js', 'Vercel', 'Tailwind'],
          timeline: '1~2주',
          starting: '50만원~',
          ideal: '신제품 출시, 이벤트 페이지, 예약 받기, 자료 다운로드',
        },
        {
          key: 'business', title: 'Business Website', titleKo: '기업 홈페이지',
          desc: '회사 소개·서비스·연락처까지 5~10페이지. 브랜드 톤에 맞춘 커스텀 디자인.',
          tagline: '회사의 첫인상을 책임지는 정식 홈페이지. 템플릿이 아닌 우리만의 디자인',
          features: ['브랜드 톤 커스텀 디자인', '5~10개 페이지 (회사 소개·서비스·연락처 등)', '관리자에서 콘텐츠 수정 가능', '문의·견적 폼 + 이메일/문자 알림', 'SEO 최적화 (검색 노출)', '다국어 지원 (선택)', '구글 지도 연동'],
          tech: ['React', 'Next.js', 'Headless CMS', 'PostgreSQL'],
          timeline: '3~6주',
          starting: '150만원~',
          ideal: '신생 기업, 리뉴얼, 글로벌 진출, B2B 영업 도구',
        },
        {
          key: 'webapp', title: 'Web Application', titleKo: '웹 애플리케이션',
          desc: '로그인·대시보드·실시간 기능이 핵심인 SaaS형 웹 서비스. 기획부터 같이.',
          tagline: '단순 정보 전달이 아닌, 사용자가 \'쓰는\' 서비스. 매칭·예약·구독 모델 등',
          features: ['회원가입·로그인 (소셜 포함)', '실시간 데이터 동기화', '사용자별 맞춤 화면', '결제·구독 모델 (선택)', '관리자 대시보드 포함', 'API 설계·문서화', '확장 가능한 아키텍처'],
          tech: ['React', 'Node.js', 'PostgreSQL', 'WebSocket', 'Redis'],
          timeline: '8~16주',
          starting: '500만원~',
          ideal: 'SaaS, 매칭 플랫폼, 커뮤니티, 협업 도구',
        },
        {
          key: 'ecommerce', title: 'E-commerce', titleKo: '쇼핑몰',
          desc: '상품·장바구니·결제·주문 관리까지 통합 구축. 결제·배송사 연동과 필요할 때 확장 가능한 구조로 만듭니다.',
          tagline: '단순 카페24/식스샵으로는 어려운 커스텀 쇼핑 경험. 정기구독·B2B 도매 등',
          features: ['상품·옵션·재고 관리', '장바구니 + 주문/결제', 'PG 연동 (토스·아임포트·KG이니시스)', '배송 추적 (CJ대한통운 등)', '쿠폰·할인·포인트', '리뷰·Q&A', '관리자 매출/주문 대시보드', '회원 등급제'],
          tech: ['Next.js', 'Node.js', 'PostgreSQL', 'Toss Payments'],
          timeline: '10~20주',
          starting: '800만원~',
          ideal: '브랜드 자사몰, 정기구독 박스, B2B 도매몰, 디지털 상품',
        },
        {
          key: 'admin', title: 'Admin Dashboard', titleKo: '관리자 시스템',
          desc: '데이터 시각화와 운영자용 관리 도구. 비개발 직원도 바로 쓸 수 있는 UI.',
          tagline: '운영팀이 매일 쓰는 도구. 엑셀로 관리하던 일을 화면 하나로',
          features: ['역할별 권한 관리 (관리자/직원)', '실시간 매출·방문자 차트', '엑셀 가져오기/내보내기', '검색·필터·정렬 (대량 데이터 OK)', '활동 로그 (누가 뭘 했나)', '알림 설정 (이메일/슬랙)', '다크모드'],
          tech: ['React', 'Recharts', 'Node.js', 'PostgreSQL'],
          timeline: '4~10주',
          starting: '300만원~',
          ideal: '기존 서비스에 운영 도구 필요, 데이터 시각화, ERP 보조',
        },
        {
          key: 'ops', title: 'Internal Ops Console', titleKo: '운영 의사결정 콘솔',
          desc: '엑셀로 굴리던 검토·심사·결정 업무를 라이브 콘솔로. 룰이 점수를 매기고, 우선순위 큐가 자동으로 정리됩니다.',
          tagline: '엑셀로 굴리던 검토·심사 작업을 한 화면 콘솔로 — 룰이 점수, 우선순위는 자동',
          features: ['항목별 룰 기반 자동 점수 (◎/○/△/✗)', '필터·검색·정렬 (수십~수백 건)', '우선순위 큐와 상태 추적', '이유 추적 — 왜 통과했고 왜 거절됐는지', 'CSV·구글시트 동기화 (선택)', '권한별 화면 (검토자/관리자)', '히스토리 로그'],
          tech: ['React', 'Vue', 'Node.js', 'PostgreSQL'],
          timeline: '2~6주',
          starting: '200만원~',
          ideal: '외주 공고 심사, 입찰 검토, 채용 1차 스크리닝, 제품 큐레이션',
        },
      ],
    },
    works: { label: 'WORKS', title: '최근 프로젝트', viewAll: '전체 보기' },
    why: {
      label: 'WHY CUSTOM',
      title: '왜 직접 개발한 홈페이지여야 할까요?',
      desc1: '아임웹, Wix 같은 빌더는 간편하지만 한계가 명확합니다.',
      desc2: '비즈니스가 성장할수록 직접 개발한 홈페이지의 가치가 커집니다.',
      benefitsLabel: 'KEY BENEFITS',
      benefitsTitle: '직접 개발한 홈페이지가 비즈니스에 주는 4가지 가치',
    },
    cta: {
      title: '기업 홈페이지 준비, 함께 시작할까요?',
      desc1: '무료 상담',
      desc2: '을 통해 필요한 기능과 예산을 함께 정리해드립니다.',
      btn: '무료 상담 신청',
    },
    banner: { tag: '// STUDIO NOTE', title: '홈페이지공방', desc: '고객 문의가 잘 이어지는 홈페이지, 납품 후에도 계속 관리합니다' },
    capabilities: {
      label: 'WHAT I CAN BUILD',
      title: '이런 기능들,\n다 만들어드릴 수 있어요',
      desc: '복잡한 기술 용어 대신, 사용자가 실제로 쓰는 모습으로 설명드려요.\n어떤 게 필요한지 모르시겠으면 1:1 상담에서 같이 정해드립니다.',
      items: [
        {
          key: 'auth',
          title: '회원가입 · 로그인',
          desc: '카카오·구글·네이버로 한 번에 가입. 비밀번호 찾기, 자동 로그인, 본인 인증까지 안전하게.',
          tags: ['Kakao', 'Google', 'Naver', 'OAuth', 'JWT'],
        },
        {
          key: 'payment',
          title: '결제 시스템',
          desc: '신용카드·계좌이체·간편결제(카카오페이·토스)까지. 정기 결제, 환불 처리도 포함.',
          tags: ['Toss', 'PortOne', 'KakaoPay', 'Stripe'],
        },
        {
          key: 'realtime',
          title: '실시간 채팅 · 알림',
          desc: '메시지가 오자마자 바로 뜨고, 새 알림이 화면에 즉시 표시되는 실시간 기능.',
          tags: ['WebSocket', 'Socket.IO', 'SSE'],
        },
        {
          key: 'ai',
          title: 'AI 기능 연동',
          desc: 'ChatGPT·Claude 같은 AI를 우리 서비스 안에서 동작하게. 챗봇, 자동 요약, 번역 등.',
          tags: ['OpenAI', 'Claude', 'Gemini'],
        },
        {
          key: 'file',
          title: '사진 · 파일 업로드',
          desc: '큰 사진도 자동으로 줄여서 빠르게 보여주기. 동영상·문서까지 안전하게 보관.',
          tags: ['AWS S3', 'Cloudinary', 'Sharp', 'CDN'],
        },
        {
          key: 'chart',
          title: '관리자 대시보드',
          desc: '매출·방문자·주문 현황을 차트와 그래프로 한눈에. 엑셀로 내보내기까지.',
          tags: ['Recharts', 'Chart.js', 'Excel Export'],
        },
        {
          key: 'search',
          title: '검색 · 자동완성',
          desc: '타이핑하는 동안 추천어가 뜨고, 오타가 있어도 결과를 찾아주는 똑똑한 검색.',
          tags: ['Elasticsearch', 'Algolia', 'Fuse.js'],
        },
        {
          key: 'push',
          title: '푸시 알림',
          desc: '웹에서 \"새 메시지 도착\" 같은 알림을 보내서, 사용자가 다시 들어오게.',
          tags: ['FCM', 'Web Push', 'OneSignal'],
        },
        {
          key: 'seo',
          title: '구글 검색 노출',
          desc: '구글에서 우리 사이트가 잘 보이도록 최적화. 로딩 속도, 메타 정보, 사이트맵까지.',
          tags: ['Next.js SSR', 'Sitemap', 'OG Image', 'Core Web Vitals'],
        },
      ],
    },
    process: {
      label: 'HOW WE WORK',
      headline: '아이디어부터\n런칭까지,\n네 단계로',
      desc: '체계적인 프로세스로 프로젝트의 시작과 끝을 함께합니다.',
      steps: [
        { num: '01', tag: 'DISCOVERY', title: '발견', desc: '비즈니스 목표와 사용자 니즈를 파악하고, 프로젝트 범위·일정·예산을 함께 설계합니다.' },
        { num: '02', tag: 'DESIGN', title: '설계', desc: '정보 구조와 와이어프레임을 거쳐, 브랜드 정체성에 맞는 UI/UX 디자인을 완성합니다.' },
        { num: '03', tag: 'DEVELOP', title: '개발', desc: '프론트엔드·백엔드·DB를 한 사람의 손에서 통합해, 빠르고 일관된 구현을 진행합니다.' },
        { num: '04', tag: 'LAUNCH', title: '런칭', desc: '실서버 배포부터 도메인·SSL·SEO 최적화, 운영 가이드까지 안정적으로 이양합니다.' },
      ],
    },
    quickDock: {
      quote: '견적 문의',
      chat: '1:1 상담',
      top: '맨 위로',
    },
    inquiryCTA: {
      prefix: '지금',
      suffix: '을 문의하세요',
      words: ['기업 홈페이지', '예약·문의 폼', '관리자 페이지', '쇼핑몰', '모바일 대응', '랜딩 페이지', '운영 자동화'],
      primary: '1:1 문의하기',
    },
    availability: {
      label: '이번 달 1건 신규 의뢰 접수 가능',
      hint: '평일 24시간 내 답변',
      cta: '의뢰하기',
    },
    faq: {
      label: 'FAQ',
      title: '자주 묻는 질문',
      desc: '계약 전에 가장 많이 받는 질문들을 모았습니다.\n더 궁금한 점은 1:1 문의로 편하게 물어봐주세요.',
      items: [
        { q: '제작 기간은 얼마나 걸리나요?', a: '랜딩 페이지는 1~2주, 일반 홈페이지(5~10페이지)는 3~6주, 관리자·예약 기능이 포함된 종합 플랫폼은 8~16주 정도 소요됩니다.\n범위·디자인 복잡도에 따라 달라지며, 첫 상담 후 일정표를 함께 정리해드립니다.' },
        { q: '비용은 어떻게 책정되나요?', a: '무료 상담으로 범위를 확정한 뒤 고정가로 견적을 드립니다 (시간당이 아닌 결과물 기반).\n계약 후 추가 요청이 나오면, 별도 견적으로 사전 동의받고 진행합니다 — "공사 끝나고 청구서가 늘어나는" 일은 없습니다.' },
        { q: '소스코드는 누가 소유하나요?', a: '잔금 완납 시 소스코드와 디자인 원본을 모두 클라이언트가 소유합니다.\nGitHub 저장소·디자인 파일·운영 가이드를 함께 인계해, 추후 다른 개발자에게 맡기더라도 종속 없이 이어갈 수 있습니다.' },
        { q: '도메인·서버 비용은 별도인가요?', a: '네, 도메인(연 1.5~2만원)과 호스팅(월 2~5만원)은 클라이언트 명의로 직접 가입하시는 걸 권장드립니다.\n이렇게 하면 개발자가 바뀌어도 인프라 소유권이 안전합니다. 가입·세팅 가이드를 직접 도와드립니다.' },
        { q: '수정은 몇 번까지 가능한가요?', a: '디자인 시안 단계에서 2회, 개발 완료 후 마이너 수정 1회까지 포함됩니다.\n그 이후는 시간 단위 유지보수로 진행되며, 월 정기 유지보수 계약도 가능합니다.' },
        { q: '운영·유지보수도 가능한가요?', a: '런칭 후 1개월간은 무상 버그 대응을 보장합니다.\n그 이후 기능 추가·운영 대응이 필요한 경우, 월 정액 또는 시간당 단위로 유연하게 진행 가능합니다.' },
        { q: '계약 전에 포트폴리오를 더 볼 수 있나요?', a: '네, 1:1 상담 요청 시 진행 중인 작업·과거 사례·코드 샘플까지 자세히 공유드립니다.\n비공개 NDA 프로젝트도 별도 안내가 가능합니다.' },
      ],
    },
    testimonials: {
      label: 'CLIENT VOICES',
      title: '함께한 분들의 이야기',
      desc: '솔직한 피드백이 가장 큰 자산입니다.',
      items: [
        { client: '김OO님', initial: '김', tag: '반응형 웹', tagKey: 'web', body: '브랜드 톤을 잘 살린 웹사이트가 완성됐어요. 작업 과정도 투명하게 공유해주셔서 믿고 맡겼습니다.' },
        { client: '이OO님', initial: '이', tag: '풀스택 개발', tagKey: 'api', body: '복잡한 로직까지 한 사람이 깔끔하게 구현해주셔서, 커뮤니케이션 비용이 정말 적었습니다.' },
        { client: '박OO님', initial: '박', tag: 'UI/UX 디자인', tagKey: 'ux', body: '템플릿이 아닌 우리만의 디자인을 가지게 됐어요. 사용자 경험까지 신경 써주신 게 보입니다.' },
        { client: '최OO님', initial: '최', tag: '플랫폼 구축', tagKey: 'web', body: '기획부터 같이 정리해주신 덕분에 길을 잃지 않고 진행할 수 있었어요. 결과물도 만족스럽습니다.' },
        { client: '윤OO님', initial: '윤', tag: 'API 연동', tagKey: 'api', body: '결제·배송 외부 API 연동을 깔끔하게 처리해주셔서 운영 단계에서도 문제가 없었어요.' },
        { client: '송OO님', initial: '송', tag: '랜딩 페이지', tagKey: 'web', body: '예산 안에서 최대치의 결과물을 만들어주셨어요. 약속 일정도 정확하게 지켜주셨습니다.' },
        { client: '한OO님', initial: '한', tag: '관리자 대시보드', tagKey: 'ux', body: '운영 편의성을 정말 잘 고려해주셨어요. 비개발 직원도 바로 적응할 수 있는 화면이 나왔습니다.' },
      ],
    },
    pricing: {
      label: 'PRICING',
      title: '필요한 만큼, 정확하게.',
      desc: '프로젝트 규모에 맞춘 3단계 — 견적은 상담 후 확정됩니다.',
      comparisonHeader: '패키지 설명',
      ctaText: '상담받기',
      smallNote: '✱ 모든 플랜은 무료 상담 후 정식 견적을 확정합니다.',
      discountLabel: '80% 할인',
      tiers: [
        {
          key: 'standard',
          name: 'STANDARD',
          listPrice: '1,500,000원',
          price: '300,000원',
          descTitle: 'Web Page 반응형 웹사이트',
          descBody: '1~3페이지 랜딩페이지 제작, 반응형 웹, 문의 폼 포함 (홈페이지 배포 X)',
          prefill: {
            projectType: '웹 개발',
            budget: '100만원 이하',
            description: 'Web Page 반응형 웹사이트(랜딩페이지 1~3P) 제작 문의드립니다.',
          },
        },
        {
          key: 'deluxe',
          name: 'DELUXE',
          listPrice: '7,500,000원',
          price: '1,500,000원',
          descTitle: 'Multi Page 기업 웹사이트',
          descBody: '다중 페이지 홈페이지, 반응형 웹, 문의/상담 기능, 도메인·SSL 배포 포함',
          prefill: {
            projectType: '웹 개발',
            budget: '100~300만원',
            description: '기업 웹사이트(다중 페이지) 제작 문의드립니다.',
          },
        },
        {
          key: 'premium',
          name: 'PREMIUM',
          listPrice: '25,000,000원',
          price: '5,000,000원',
          descTitle: '풀스택 웹 플랫폼 + 관리자',
          descBody: '관리자 대시보드, 로그인·회원, DB 연동, 실서버 배포까지 풀스택 일괄',
          prefill: {
            projectType: '웹 개발',
            budget: '500~1000만원',
            description: '풀스택 웹 플랫폼 + 관리자 대시보드 제작 문의드립니다.',
          },
        },
      ],
      features: [
        { key: 'design',       label: '맞춤 디자인 제공', values: [true, true, true] },
        { key: 'responsive',   label: '반응형 웹',        values: [true, true, true] },
        { key: 'crossbrowser', label: '크로스 브라우징',   values: [true, true, true] },
        { key: 'source',       label: '소스 코드 제공',    values: [true, true, true] },
        { key: 'wireframe',    label: '화면설계서',        values: [false, false, true] },
        { key: 'comments',     label: '코드 구조 주석',    values: [false, true, true] },
      ],
      quantitative: [
        { key: 'pages',     label: '페이지 수', values: ['1~3페이지', '5~10페이지', '12+페이지'] },
        { key: 'workdays',  label: '작업일',   values: ['10일', '21일', '45일'] },
        { key: 'revisions', label: '수정 횟수', values: ['3회', '5회', '제한없음'] },
      ],
    },
    maintenance: {
      eyebrow: '> maintenance/',
      title: '런칭 후에도 계속 살아있는 홈페이지',
      desc: '만드는 것으로 끝나지 않아요. 월 정기 관리로 사이트가 언제나 정상 작동하도록.',
      popularBadge: '가장 인기',
      priceSuffix: '/월',
      ctaLabel: '문의하기',
      note: '* 실제 수정 빈도와 투입 시간을 2~3개월 기록한 뒤 가격·제공시간을 조정합니다. "간단한 수정 무제한"은 포함하지 않습니다.',
      tiers: [
        {
          key: 'care',
          name: '안심관리',
          tagline: '기본 점검 + 소소한 수정',
          price: '12만원',
          items: [
            '가동 여부 · SSL · 백업 점검 (월 1회)',
            '월 30분 이내 경미한 텍스트/이미지 수정',
            '월 1회 상태 리포트',
            '이메일 요청 접수 (영업일 4시간 내 1차 응답)',
          ],
          prefill: {
            projectType: '유지보수',
            budget: '100만원 이하',
            description: '[유지관리] 안심관리 (월 12만원) 상담 요청드립니다. 기본 점검 + 월 30분 내 경미한 수정 위주.',
          },
        },
        {
          key: 'ops',
          name: '운영관리',
          tagline: '안심관리 + 월 2시간 수정 + 리포트',
          price: '25만원',
          popular: true,
          items: [
            '안심관리 항목 전체 포함',
            '월 2시간 콘텐츠/디자인 수정',
            '방문 수 · 문의 수 월간 요약 보고',
            '미사용 시간 최대 1개월 이월',
            '이메일 · 카카오 접수 (영업일 4시간 내 1차 응답)',
          ],
          prefill: {
            projectType: '유지보수',
            budget: '100만원 이하',
            description: '[유지관리] 운영관리 (월 25만원) 상담 요청드립니다. 월 2시간 수정 + 방문/문의 요약 보고 포함.',
          },
        },
        {
          key: 'grow',
          name: '성장관리',
          tagline: '운영관리 + 개선 · 우선 대응 · 무상 긴급 1회',
          price: '35~50만원',
          items: [
            '운영관리 항목 전체 포함',
            '월 4~5시간 개선 작업 (성능 · UX · SEO)',
            '검색 · 분석 기반 개선 제안',
            '요청 우선 대응 (영업일 2시간 내 1차 응답)',
            '월 1회 무상 긴급 대응 포함',
          ],
          prefill: {
            projectType: '유지보수',
            budget: '100만원 이하',
            description: '[유지관리] 성장관리 (월 35~50만원) 상담 요청드립니다. 개선 작업 + 우선 대응 + 무상 긴급 대응 1회 포함.',
          },
        },
      ],
    },
    aiPreview: {
      label: '// AI_PREVIEW',
      title: 'AI로 홈페이지 시안 먼저 받아보기',
      desc: '업종과 원하는 분위기를 알려주시면 AI가 헤드라인·구성안을 만들어드려요. 실제 제작은 언제나 사람이 직접 코드로 완성합니다.',
      businessTypes: ['카페/음식점', '병원/의원', '학원/교육', '쇼핑몰/커머스', '뷰티/살롱', 'IT/스타트업', '기타'],
      siteGoals: ['예약 늘리기', '판매 늘리기', '문의 늘리기', '브랜드 소개', '채용'],
      moods: ['미니멀', '따뜻한', '고급스러운', '발랄한', '신뢰감 있는'],
      form: {
        businessType: '업종',
        siteGoal: '사이트 목표',
        mood: '원하는 분위기',
        mustHave: '꼭 필요한 기능',
        mustHavePh: '예: 온라인 예약, 실시간 채팅, 다국어 지원',
        referenceSite: '참고 사이트 (선택)',
        referenceSitePh: '마음에 드는 사이트 URL',
        email: '이메일',
        emailPh: 'name@email.com',
      },
      submit: 'AI 시안 받기',
      submitting: 'AI가 시안을 만들고 있어요...',
      errors: {
        missing_fields: '필수 항목을 모두 입력해주세요.',
        input_too_long: '입력 내용이 너무 길어요. 조금 줄여주세요.',
        rate_limited: '오늘 생성 가능 횟수를 모두 사용했어요. 내일 다시 시도해주세요.',
        db_unavailable: '지금 서비스 점검 중이에요. 잠시 후 다시 시도해주세요.',
        ai_unavailable: 'AI 시안 생성이 잠시 꺼져 있어요.',
        save_failed: '저장에 실패했어요. 다시 시도해주세요.',
        generation_failed: 'AI 시안 생성에 실패했어요.',
        unknown: '알 수 없는 오류가 발생했어요.',
        fallbackCta: 'AI 없이 바로 상담 신청하기',
      },
      result: {
        toneLabel: '추천 톤:',
      },
      cta: '이 방향으로 실제 제작 상담받기',
      prefillPrefix: 'AI 시안을 참고해서 프로젝트를 문의드려요.',
      chat: {
        botLabel: '> DEV.VIBE AI',
        heroTitle: '어떤 홈페이지를 만들어드릴까요?',
        heroDesc: '간단히 알려주시면 AI가 홈페이지 시안을 만들어드려요.',
        promptPlaceholder: '예: 조용한 분위기의 카페 웹사이트, 예약 기능 필요해요...',
        suggestions: [
          { emoji: '🏪', text: '카페/음식점 웹사이트' },
          { emoji: '📅', text: '예약 시스템 있는 사이트' },
          { emoji: '🛍️', text: '온라인 쇼핑몰' },
          { emoji: '🎨', text: '브랜드 랜딩 페이지' },
        ],
        attachLabel: '첨부 (준비 중)',
        sendLabel: '전송',
        emailAsk: (prompt) => `좋아요! "${prompt}" 시안을 만들어볼게요. 결과 받으실 이메일 주소를 알려주세요.`,
        emailPlaceholder: 'name@email.com',
        emailInvalid: '유효한 이메일 주소를 입력해주세요.',
        promptEmpty: '무엇을 만들지 알려주세요.',
        typingLabel: 'AI가 시안을 만들고 있어요',
        resultIntro: '완성됐어요! 아래 시안 확인해보세요 👇',
        fallbackIntro: '앗, 아직 AI 시안 생성 기능은 준비 중이에요. 대신 사람이 직접 초안을 만들어드릴게요.',
        fallbackCta: '상담 페이지로 이동',
        contactCta: '이 시안대로 상담하기',
        restart: '처음부터 다시',
        userLabel: '나',
        botAvatar: 'AI',
      },
    },
    reactions: {
      title: '> 어떠셨어요?',
      aria: (emoji, count) => `${emoji} 반응 (${count}개)`,
    },
    collection: {
      trigger: '> saved',
      header: 'saved.json',
      empty: '저장한 프로젝트가 여기 모여요.\n📌 아이콘으로 저장해보세요.',
      clearAll: '모두 지우기',
      clearConfirm: '저장한 프로젝트를 모두 지울까요?',
      close: '닫기',
    },
  },
  en: {
    nav: { services: 'SERVICES', references: 'DESIGNS', portfolio: 'PORTFOLIO', about: 'ABOUT', contact: 'CONTACT' },
    hero: {
      heroCard: {
        headerBar: 'devvibe — main',
        ariaLabel: 'Developer profile code card',
        files: [
          {
            key: 'profile',
            name: 'profile.ts',
            lang: 'TypeScript',
            lines: [
              { kind: 'comment',     code: '// Just go for it.',                                            accent: 'comment' },
              { kind: 'spacer',      code: '',                                                              accent: 'comment' },
              { kind: 'keyword',     code: 'export const profile = {',                                      accent: 'keyword' },
              { kind: 'declaration', code: '  name: "DEVIBE",',                                             accent: 'string'  },
              { kind: 'declaration', code: '  role: "Full-Stack Dev Partner",',                             accent: 'string'  },
              { kind: 'array',       code: '  builds: ["websites", "shops", "admin tools", "landing"],',    accent: 'string'  },
              { kind: 'declaration', code: '  stack: ["React", "Node", "TypeScript", "PostgreSQL"],',       accent: 'string'  },
              { kind: 'declaration', code: '  status: "available",  // 1 slot this month',                  accent: 'string'  },
              { kind: 'declaration', code: '  reply: "24h on weekdays",',                                   accent: 'string'  },
              { kind: 'declaration', code: '  contact: "/contact",',                                        accent: 'string'  },
              { kind: 'keyword',     code: '};',                                                            accent: 'keyword' },
            ],
          },
          {
            key: 'stack',
            name: 'stack.ts',
            lang: 'TypeScript',
            lines: [
              { kind: 'comment',     code: '// Tech stack' },
              { kind: 'spacer',      code: '' },
              { kind: 'keyword',     code: 'export const stack = {' },
              { kind: 'declaration', code: '  frontend: ["React", "Next.js", "TypeScript", "Tailwind"],' },
              { kind: 'declaration', code: '  backend:  ["Node.js", "Express", "PostgreSQL", "Redis"],' },
              { kind: 'declaration', code: '  cloud:    ["AWS", "Render", "Vercel", "Cloudflare"],' },
              { kind: 'declaration', code: '  tools:    ["Docker", "GitHub Actions", "Figma"],' },
              { kind: 'declaration', code: '  yearsExp: 3,' },
              { kind: 'keyword',     code: '};' },
            ],
          },
          {
            key: 'status',
            name: 'status.ts',
            lang: 'TypeScript',
            lines: [
              { kind: 'comment',     code: "// This month's availability" },
              { kind: 'spacer',      code: '' },
              { kind: 'keyword',     code: 'export const status = {' },
              { kind: 'declaration', code: '  available: true,' },
              { kind: 'declaration', code: '  slotsThisMonth: 1,' },
              { kind: 'declaration', code: '  replyTime: "24h on weekdays",' },
              { kind: 'declaration', code: '  currentProjects: 2,' },
              { kind: 'declaration', code: '  nextSlotFrom: "available now",' },
              { kind: 'declaration', code: '  contact: "/contact",' },
              { kind: 'keyword',     code: '};' },
            ],
          },
        ],
        sidebar: {
          explorerLabel: 'EXPLORER',
          projectLabel: 'DEV.VIBE',
          folders: [
            { name: 'src', files: ['profile.ts', 'stack.ts', 'status.ts'] },
            { name: 'docs', files: ['README.md'] },
          ],
        },
        statusBar: {
          branch: 'main',
          errors: 0,
          warnings: 0,
          encoding: 'UTF-8',
          liveLabel: 'Live',
          paletteHint: '⌘K',
          paletteTooltip: 'Command Palette (Ctrl/⌘ + K)',
        },
        primaryCta: 'Start a project →',
        secondaryCta: 'View portfolio',
      },
    },
    intro: {
      label: 'WHO WE ARE',
      title: 'The studio you call\nwhen you need a company site.',
      desc: '홈페이지공방 keeps your inquiries flowing on desktop and mobile alike, builds the admin, booking, and integration features your team actually needs, and stays around to maintain it after launch. Built to extend when you need it — so the next person on your team can pick right up.',
    },
    about: {
      mission: '홈페이지공방 is a homepage partner: we build responsive company sites that keep customer inquiries flowing across desktop and mobile, develop the admin, booking, and integration features you need in-house, and keep maintaining them long after launch.',
    },
    parallaxBridge: {
      top: 'HOMEPAGE-GONGBANG · CRAFTED IN CODE',
      bottom: 'MADE TO LAST · SINCE 2026',
    },
    comingSoon: {
      label: 'Coming Soon',
      title: 'Just a moment!',
      body: "This feature is being finalized. It'll launch soon — in the meantime, please reach out via email or the Kakao open chat.",
      aiPreviewTitle: 'AI draft generation is in preparation',
      aiPreviewBody: "It's in internal testing right now. Launching soon — until then, tell us the direction you want in the consultation form below and a human will draft it for you.",
      contactCta: 'Start a consultation',
    },
    customerProblems: {
      eyebrow: '> problems/',
      headline: 'Do these sound familiar?',
      caption: '홈페이지공방 has answers to all three.',
      cards: [
        {
          num: 'PROBLEM 01',
          problem: 'Mobile inquiries keep falling through the cracks',
          solution: 'We tune the site so inquiries and bookings hold up on desktop and mobile alike, and make sure the contact form opens within 3 seconds.',
        },
        {
          num: 'PROBLEM 02',
          problem: 'No admin panel — every content edit needs a developer',
          solution: 'We build the admin tools and automations that cut repetitive work, so your team can update content directly.',
        },
        {
          num: 'PROBLEM 03',
          problem: 'What happens to the site if the developer walks away?',
          solution: 'The contract spells out source code and data handover, and every delivery ships with a 30-day free bug-fix window plus optional monthly maintenance.',
        },
      ],
    },
    trustCompliance: {
      ariaLabel: 'Contract & maintenance overview',
      items: [
        { icon: '[ 01 ]', label: 'Freelance contract', sub: '3.3% withholding supported' },
        { icon: '[ 02 ]', label: 'Source code handover', sub: 'Written into the contract' },
        { icon: '[ 03 ]', label: '30-day free bug fixes', sub: 'Applied automatically after delivery' },
        { icon: '[ 04 ]', label: 'Monthly maintenance plans', sub: '₩120k–₩500k / month' },
      ],
    },
    starterProducts: {
      eyebrow: '> starter/',
      headline: 'Quick-start compact products',
      caption: 'Get a feel for how we work before committing to a full company site. Trials can convert into a formal contract.',
      tagLabel: 'STARTER',
      discountLabel: '80% OFF',
      list: [
        {
          name: 'Single landing page',
          body: 'One page for a product or campaign. Responsive with a contact form.',
          listPrice: 'from ₩1,500k',
          price: 'from ₩300k',
          cta: 'Start consult →',
          prefill: {
            projectType: 'Web Development',
            budget: 'Under $1k',
            description: '[STARTER] Requesting a consult for a single landing page (product/campaign, responsive, contact form).',
          },
        },
        {
          name: 'Business-card site (3 pages)',
          body: 'About / services / contact. Basic SEO and deployment included.',
          listPrice: 'from ₩2,000k',
          price: 'from ₩400k',
          cta: 'Start consult →',
          prefill: {
            projectType: 'Web Development',
            budget: 'Under $1k',
            description: '[STARTER] Requesting a consult for a 3-page business-card site (about, services, contact, basic SEO, deployment).',
          },
        },
        {
          name: 'Inquiry-form kit',
          body: 'Add a contact form and auto-reply email to an existing site.',
          listPrice: 'from ₩1,250k',
          price: 'from ₩250k',
          cta: 'Start consult →',
          prefill: {
            projectType: 'Maintenance',
            budget: 'Under $1k',
            description: '[STARTER] Requesting a consult for adding an inquiry form and auto-reply email to an existing site.',
          },
        },
      ],
      bridge: '> Ready for a full company site? See the plans below ↓',
    },
    services: {
      label: 'SERVICES',
      title: 'The deliverable\nyou need, built.',
      list: [
        {
          key: 'landing', title: 'Landing Page', titleKo: 'Landing',
          desc: 'Single-page sites for product launches and campaigns. Conversion-tuned, live in 1–2 weeks.',
          tagline: 'A single page that announces a new product fast and turns visitors into action',
          features: ['Responsive design (desktop & mobile)', 'Inquiry / booking form with email alerts', 'Google Analytics & Pixel integration', 'Basic SEO setup', 'Domain, HTTPS, CDN deployment', 'Content editing guide'],
          tech: ['React', 'Next.js', 'Vercel', 'Tailwind'],
          timeline: '1–2 weeks',
          starting: 'from $400',
          ideal: 'Product launches, event pages, lead magnets, downloads',
        },
        {
          key: 'business', title: 'Business Website', titleKo: 'Business',
          desc: '5–10 pages from company intro to services and contact. Custom design that fits your brand.',
          tagline: 'Your company\'s first impression — fully custom, not a template',
          features: ['Brand-tone custom design', '5–10 pages (company, services, contact, etc.)', 'CMS for content editing', 'Inquiry/quote forms with email/SMS alerts', 'SEO optimization', 'Multi-language support (optional)', 'Google Maps integration'],
          tech: ['React', 'Next.js', 'Headless CMS', 'PostgreSQL'],
          timeline: '3–6 weeks',
          starting: 'from $1,200',
          ideal: 'New companies, renewals, global expansion, B2B sales',
        },
        {
          key: 'webapp', title: 'Web Application', titleKo: 'Web App',
          desc: 'SaaS-style products built around login, dashboards and real-time features.',
          tagline: 'Not just information — a product users actually use. Matching, booking, subscription, etc.',
          features: ['Sign-up & login (social included)', 'Real-time data sync', 'Per-user personalized views', 'Payment / subscription (optional)', 'Built-in admin dashboard', 'API design & documentation', 'Scalable architecture'],
          tech: ['React', 'Node.js', 'PostgreSQL', 'WebSocket', 'Redis'],
          timeline: '8–16 weeks',
          starting: 'from $4,000',
          ideal: 'SaaS, matching platforms, communities, collaboration tools',
        },
        {
          key: 'ecommerce', title: 'E-commerce', titleKo: 'Shop',
          desc: 'End-to-end store: products, cart, checkout, orders — payment and shipping integrations included, built to extend later.',
          tagline: 'Custom shopping experiences beyond Shopify templates — subscriptions, B2B wholesale, etc.',
          features: ['Product, option, inventory management', 'Cart, orders, checkout', 'Payment gateways (Stripe / Toss / etc.)', 'Shipping tracking integration', 'Coupons, discounts, loyalty points', 'Reviews & Q&A', 'Sales / orders admin dashboard', 'Membership tiers'],
          tech: ['Next.js', 'Node.js', 'PostgreSQL', 'Stripe'],
          timeline: '10–20 weeks',
          starting: 'from $6,500',
          ideal: 'Brand DTC, subscription boxes, B2B wholesale, digital products',
        },
        {
          key: 'admin', title: 'Admin Dashboard', titleKo: 'Admin',
          desc: 'Data visualization and ops tools designed for non-technical staff to pick up instantly.',
          tagline: 'The tool your ops team uses every day. Replace spreadsheets with a single screen.',
          features: ['Role-based permissions (admin / staff)', 'Real-time sales & traffic charts', 'Excel import / export', 'Search, filter, sort (handles big data)', 'Activity logs (who did what)', 'Alert settings (email / Slack)', 'Dark mode'],
          tech: ['React', 'Recharts', 'Node.js', 'PostgreSQL'],
          timeline: '4–10 weeks',
          starting: 'from $2,500',
          ideal: 'Internal tools, data visualization, ERP supplements',
        },
        {
          key: 'ops', title: 'Internal Ops Console', titleKo: 'Ops',
          desc: 'Turn spreadsheet-driven review, screening, and decision work into a live console. Rules score each item; the priority queue auto-sorts.',
          tagline: 'Spreadsheet review work, in one console — rules score, priority sorts itself.',
          features: ['Rule-based auto-scoring per item (top / good / mixed / skip)', 'Filter, search, sort (dozens to hundreds of items)', 'Priority queue + status tracking', 'Reason trace — why it passed, why it didn’t', 'CSV / Google Sheets sync (optional)', 'Role-based screens (reviewer / admin)', 'History log'],
          tech: ['React', 'Vue', 'Node.js', 'PostgreSQL'],
          timeline: '2–6 weeks',
          starting: 'from $1,800',
          ideal: 'Inbound lead review, bid screening, hiring first-pass, product curation',
        },
      ],
    },
    works: { label: 'WORKS', title: 'Recent Projects', viewAll: 'View all' },
    why: {
      label: 'WHY CUSTOM',
      title: 'Why a custom-built site?',
      desc1: 'Builders like I\'mWeb and Wix are convenient but limited.',
      desc2: 'As your business grows, owning your site truly starts to pay off.',
      benefitsLabel: 'KEY BENEFITS',
      benefitsTitle: '4 Ways a Custom-Built Site Pays Off',
    },
    cta: {
      title: 'Ready to plan your company site?',
      desc1: 'Free consultation',
      desc2: ' — we\'ll help you narrow down features and budget together.',
      btn: 'Request Free Consultation',
    },
    banner: { tag: '// STUDIO NOTE', title: '홈페이지공방', desc: 'A site that keeps inquiries flowing — and we stay on to maintain it' },
    capabilities: {
      label: 'WHAT I CAN BUILD',
      title: 'All these features,\nbuilt for you.',
      desc: 'Plain-language descriptions, not technical jargon — so you can see exactly what you get.\nNot sure what you need? Let\'s figure it out together in a 1:1 chat.',
      items: [
        {
          key: 'auth',
          title: 'Sign-up & Login',
          desc: 'One-tap sign-up with Google, Apple or Kakao. Password reset, auto-login and ID verification — all secure.',
          tags: ['Google', 'Apple', 'OAuth', 'JWT'],
        },
        {
          key: 'payment',
          title: 'Payment System',
          desc: 'Credit cards, bank transfer, and modern wallets. Subscriptions and refunds handled cleanly.',
          tags: ['Stripe', 'Toss', 'PortOne'],
        },
        {
          key: 'realtime',
          title: 'Realtime Chat & Notifications',
          desc: 'Messages pop up instantly. New notifications appear on screen without a refresh.',
          tags: ['WebSocket', 'Socket.IO', 'SSE'],
        },
        {
          key: 'ai',
          title: 'AI Integration',
          desc: 'Put ChatGPT or Claude inside your product. Chatbots, auto-summary, translation, and more.',
          tags: ['OpenAI', 'Claude', 'Gemini'],
        },
        {
          key: 'file',
          title: 'Photo & File Upload',
          desc: 'Large photos auto-compressed for fast loading. Videos and documents stored safely.',
          tags: ['AWS S3', 'Cloudinary', 'Sharp', 'CDN'],
        },
        {
          key: 'chart',
          title: 'Admin Dashboard',
          desc: 'Sales, visitors, and orders shown as charts and graphs. Export to Excel included.',
          tags: ['Recharts', 'Chart.js', 'Excel Export'],
        },
        {
          key: 'search',
          title: 'Search & Autocomplete',
          desc: 'Suggestions appear as you type, and typos still find the right result.',
          tags: ['Elasticsearch', 'Algolia', 'Fuse.js'],
        },
        {
          key: 'push',
          title: 'Push Notifications',
          desc: 'Send "new message" style alerts on the web so users come back.',
          tags: ['FCM', 'Web Push', 'OneSignal'],
        },
        {
          key: 'seo',
          title: 'Google Visibility',
          desc: 'Optimized so your site shows up well on Google — speed, metadata, and sitemap included.',
          tags: ['Next.js SSR', 'Sitemap', 'OG Image', 'Core Web Vitals'],
        },
      ],
    },
    process: {
      label: 'HOW WE WORK',
      headline: 'From Idea\nTo Launch,\nIn 4 Steps',
      desc: 'A structured process that carries your project from kickoff to delivery.',
      steps: [
        { num: '01', tag: 'DISCOVERY', title: 'Discover', desc: 'We dig into your business goals and user needs, then map out scope, timeline and budget together.' },
        { num: '02', tag: 'DESIGN', title: 'Design', desc: 'Information architecture, wireframes, and a UI/UX direction that fits your brand identity.' },
        { num: '03', tag: 'DEVELOP', title: 'Develop', desc: 'Frontend, backend and database — built end-to-end by one developer, fast and consistent.' },
        { num: '04', tag: 'LAUNCH', title: 'Launch', desc: 'Production deploy, domain · SSL · SEO setup, and an operations handoff you can rely on.' },
      ],
    },
    quickDock: {
      quote: 'Get a Quote',
      chat: '1:1 Chat',
      top: 'Back to top',
    },
    inquiryCTA: {
      prefix: 'Inquire about your',
      suffix: 'now',
      words: ['Company Site', 'Inquiry & Booking Form', 'Admin Panel', 'Online Shop', 'Mobile-Ready Site', 'Landing Page', 'Ops Automation'],
      primary: 'Start 1:1 Chat',
    },
    availability: {
      label: 'Available — 1 new project this month',
      hint: 'Reply within 24h on weekdays',
      cta: 'Inquire',
    },
    faq: {
      label: 'FAQ',
      title: 'Frequently asked questions',
      desc: 'The most common questions before signing.\nNot covered here? Just send a 1:1 message.',
      items: [
        { q: 'How long does a project take?', a: 'Landing page: 1–2 weeks. Standard website (5–10 pages): 3–6 weeks. Sites with admin, booking, or integrations: 8–16 weeks.\nFinal timeline depends on scope and design complexity — we draft a roadmap together at the first consultation.' },
        { q: 'How is pricing decided?', a: 'After a free consultation to lock scope, you get a fixed-price quote (deliverable-based, not hourly).\nAny scope change after contract is quoted separately with prior approval — no surprise invoices at the end.' },
        { q: 'Who owns the source code?', a: 'On final payment, you own all source code and design assets — full stop.\nWe hand over the GitHub repo, design files, and an operations guide, so any future developer can take over without lock-in.' },
        { q: 'Are domain & hosting fees separate?', a: 'Yes. We recommend you register the domain (~$15/year) and hosting (~$5–$10/month) directly under your name.\nThis keeps infrastructure ownership safe even if you switch developers. We guide you through the setup.' },
        { q: 'How many revisions are included?', a: '2 rounds of design revisions and 1 round of minor post-launch fixes are included.\nBeyond that, it moves to hourly maintenance — monthly retainers are also available.' },
        { q: 'Do you offer ongoing maintenance?', a: 'Yes — the first month after launch includes free bug-fix coverage.\nFor new features or ongoing ops after that, monthly retainer or hourly billing works fine.' },
        { q: 'Can I see more portfolio before signing?', a: 'Absolutely. On 1:1 request, we share active work, past cases, and even code samples.\nNDA-bound work can be discussed under a mutual NDA.' },
      ],
    },
    testimonials: {
      label: 'CLIENT VOICES',
      title: 'What our clients say',
      desc: 'Honest feedback is the greatest asset.',
      items: [
        { client: 'Mr. Kim',  initial: 'K', tag: 'Responsive Web',    tagKey: 'web', body: 'A site that truly captures our brand tone. The transparent process made trust easy from day one.' },
        { client: 'Mr. Lee',  initial: 'L', tag: 'Full-Stack',        tagKey: 'api', body: 'Complex logic handled cleanly by one developer — communication overhead was nearly zero.' },
        { client: 'Ms. Park', initial: 'P', tag: 'UI/UX Design',      tagKey: 'ux',  body: 'We now have a design that is ours — not a template. The thought put into UX clearly shows.' },
        { client: 'Mr. Choi', initial: 'C', tag: 'Platform',          tagKey: 'web', body: 'Strategic guidance from planning kept us on track. We are very happy with the final outcome.' },
        { client: 'Ms. Yoon', initial: 'Y', tag: 'API Integration',   tagKey: 'api', body: 'Payment and shipping API integrations were rock solid — no operational issues post-launch.' },
        { client: 'Mr. Song', initial: 'S', tag: 'Landing Page',      tagKey: 'web', body: 'Maximum output within budget, and every deadline was hit precisely. A pleasure to work with.' },
        { client: 'Ms. Han',  initial: 'H', tag: 'Admin Dashboard',   tagKey: 'ux',  body: 'Operations were clearly considered — non-technical staff onboarded to the UI in minutes.' },
      ],
    },
    pricing: {
      label: 'PRICING',
      title: 'Right-sized, priced right.',
      desc: 'Three tiers tuned to project scope — final quote confirmed after consultation.',
      comparisonHeader: 'Package Overview',
      ctaText: 'Get a Quote',
      smallNote: '✱ Every plan is finalized with a free consultation and formal quote.',
      discountLabel: '80% OFF',
      tiers: [
        {
          key: 'standard',
          name: 'STANDARD',
          listPrice: '1,500,000원',
          price: '300,000원',
          descTitle: 'Single-page Responsive Site',
          descBody: '1–3 page landing site, responsive, contact form (hosting not included)',
          prefill: {
            projectType: 'Web Development',
            budget: 'Under $1k',
            description: 'Inquiring about a single-page responsive landing site (1–3 pages).',
          },
        },
        {
          key: 'deluxe',
          name: 'DELUXE',
          listPrice: '7,500,000원',
          price: '1,500,000원',
          descTitle: 'Multi-page Business Site',
          descBody: 'Multi-page site, responsive, inquiry & chat, domain + SSL deployment included',
          prefill: {
            projectType: 'Web Development',
            budget: '$1k–$3k',
            description: 'Inquiring about a multi-page business website build.',
          },
        },
        {
          key: 'premium',
          name: 'PREMIUM',
          listPrice: '25,000,000원',
          price: '5,000,000원',
          descTitle: 'Full-stack Platform + Admin',
          descBody: 'Admin dashboard, login/membership, DB integration, production deploy — full-stack end-to-end',
          prefill: {
            projectType: 'Web Development',
            budget: '$3k–$5k',
            description: 'Inquiring about a full-stack web platform with an admin dashboard.',
          },
        },
      ],
      features: [
        { key: 'design',       label: 'Custom Design',              values: [true, true, true] },
        { key: 'responsive',   label: 'Responsive Web',             values: [true, true, true] },
        { key: 'crossbrowser', label: 'Cross-Browser Compatible',   values: [true, true, true] },
        { key: 'source',       label: 'Source Code Included',       values: [true, true, true] },
        { key: 'wireframe',    label: 'Wireframes / Design Spec',   values: [false, false, true] },
        { key: 'comments',     label: 'Annotated Code',             values: [false, true, true] },
      ],
      quantitative: [
        { key: 'pages',     label: 'Pages',     values: ['1–3 pages', '5–10 pages', '12+ pages'] },
        { key: 'workdays',  label: 'Timeline',  values: ['10 days', '21 days', '45 days'] },
        { key: 'revisions', label: 'Revisions', values: ['3 rounds', '5 rounds', 'Unlimited'] },
      ],
    },
    maintenance: {
      eyebrow: '> maintenance/',
      title: 'A site that stays alive long after launch',
      desc: 'Building it is only half the job. Monthly care to keep everything running smoothly.',
      popularBadge: 'Most popular',
      priceSuffix: '/mo',
      ctaLabel: 'Contact',
      note: '* Pricing and included hours are adjusted after tracking each client’s real fix frequency for 2–3 months. Does NOT include unlimited "small fixes".',
      tiers: [
        {
          key: 'care',
          name: 'Care',
          tagline: 'Baseline check + small fixes',
          price: '$120',
          items: [
            'Uptime, SSL, and backup check (monthly)',
            'Up to 30 min/month of minor text / image edits',
            'Monthly status report',
            'Email intake · first reply within 4 business hours',
          ],
          prefill: {
            projectType: 'Maintenance',
            budget: 'Under $1k',
            description: '[Maintenance] Inquiring about the Care plan ($120/mo). Baseline checks + up to 30 min/month of small edits.',
          },
        },
        {
          key: 'ops',
          name: 'Ops',
          tagline: 'Care + 2 hrs/month of edits + monthly analytics report',
          price: '$250',
          popular: true,
          items: [
            'Everything in Care',
            '2 hrs / month of content / design edits',
            'Monthly visits · inquiries summary report',
            'Unused hours roll over 1 month',
            'Email · Kakao intake · first reply within 4 business hours',
          ],
          prefill: {
            projectType: 'Maintenance',
            budget: 'Under $1k',
            description: '[Maintenance] Inquiring about the Ops plan ($250/mo). 2 hrs/mo of edits + monthly report.',
          },
        },
        {
          key: 'grow',
          name: 'Grow',
          tagline: 'Ops + improvements + priority · 1 emergency call included',
          price: '$350–500',
          items: [
            'Everything in Ops',
            '4–5 hrs / month of improvement work (perf · UX · SEO)',
            'Search / analytics-driven improvement proposals',
            'Priority intake · first reply within 2 business hours',
            '1 free emergency response per month',
          ],
          prefill: {
            projectType: 'Maintenance',
            budget: 'Under $1k',
            description: '[Maintenance] Inquiring about the Grow plan ($350–500/mo). Improvements + priority + 1 emergency call.',
          },
        },
      ],
    },
    aiPreview: {
      label: '// AI_PREVIEW',
      title: 'Get an AI draft of your homepage first',
      desc: "Tell us your business and the mood you want — AI drafts a headline and page structure. The real build is always finished by hand, in code, by a person.",
      businessTypes: ['Cafe/Restaurant', 'Clinic/Hospital', 'Academy/Education', 'E-commerce', 'Beauty/Salon', 'IT/Startup', 'Other'],
      siteGoals: ['More bookings', 'More sales', 'More inquiries', 'Brand introduction', 'Hiring'],
      moods: ['Minimal', 'Warm', 'Premium', 'Playful', 'Trustworthy'],
      form: {
        businessType: 'Business type',
        siteGoal: 'Site goal',
        mood: 'Preferred mood',
        mustHave: 'Must-have features',
        mustHavePh: 'e.g. online booking, live chat, multi-language',
        referenceSite: 'Reference site (optional)',
        referenceSitePh: 'URL of a site you like',
        email: 'Email',
        emailPh: 'name@email.com',
      },
      submit: 'Get AI draft',
      submitting: 'AI is drafting your proposal...',
      errors: {
        missing_fields: 'Please fill in all required fields.',
        input_too_long: 'That input is a bit long — please shorten it.',
        rate_limited: "You've used today's generation limit. Please try again tomorrow.",
        db_unavailable: 'The service is under maintenance right now. Please try again soon.',
        ai_unavailable: 'AI drafting is temporarily disabled.',
        save_failed: 'Failed to save. Please try again.',
        generation_failed: 'AI draft generation failed.',
        unknown: 'An unknown error occurred.',
        fallbackCta: 'Skip AI, start a consultation',
      },
      result: {
        toneLabel: 'Suggested tone:',
      },
      cta: 'Start a real project with this direction',
      prefillPrefix: "I'd like to discuss a project based on this AI draft.",
      chat: {
        botLabel: '> DEV.VIBE AI',
        heroTitle: 'What homepage should I draft?',
        heroDesc: 'Tell me a little about it and AI will draft a homepage proposal.',
        promptPlaceholder: 'e.g. A quiet cafe website with online booking...',
        suggestions: [
          { emoji: '🏪', text: 'Cafe / restaurant website' },
          { emoji: '📅', text: 'Site with booking system' },
          { emoji: '🛍️', text: 'Online shop' },
          { emoji: '🎨', text: 'Brand landing page' },
        ],
        attachLabel: 'Attach (coming soon)',
        sendLabel: 'Send',
        emailAsk: (prompt) => `Great! I'll draft "${prompt}" for you. What email should we send the result to?`,
        emailPlaceholder: 'name@email.com',
        emailInvalid: 'Please enter a valid email address.',
        promptEmpty: 'Please tell me what you want to build.',
        typingLabel: 'AI is drafting your proposal',
        resultIntro: "Done! Here's your draft below 👇",
        fallbackIntro: "Ah — AI drafting isn't live yet. A person will build a draft for you instead.",
        fallbackCta: 'Go to consultation',
        contactCta: 'Consult with this draft',
        restart: 'Start over',
        userLabel: 'You',
        botAvatar: 'AI',
      },
    },
    reactions: {
      title: '> How was it?',
      aria: (emoji, count) => `${emoji} reaction (${count})`,
    },
    collection: {
      trigger: '> saved',
      header: 'saved.json',
      empty: 'Saved projects show up here.\nPin one with the 📌 icon.',
      clearAll: 'Clear all',
      clearConfirm: 'Clear all saved projects?',
      close: 'Close',
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem(STORAGE_KEY) || 'ko';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
  }, [lang]);

  const toggle = () => setLang(prev => (prev === 'ko' ? 'en' : 'ko'));

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggle, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
